// Generated by Xata Codegen 0.23.5. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "stock",
    columns: [
      { name: "exchange", type: "string" },
      { name: "ticker", type: "string" },
      { name: "name", type: "string" },
      { name: "priceCurrent", type: "float" },
      { name: "priceTarget", type: "float" },
      { name: "priceGrowth", type: "float" },
      { name: "pe", type: "float" },
      { name: "marketCap", type: "float" },
      { name: "dividendYield", type: "float" },
      { name: "annualDividend", type: "float" },
      { name: "payoutRation", type: "float" },
      { name: "roe", type: "float" },
      { name: "gfValue", type: "float" },
      { name: "gfValueMargin", type: "float" },
      { name: "isDividendAristocrat", type: "bool" },
      { name: "isDividendKing", type: "bool" },
      { name: "index", type: "link", link: { table: "index" } },
      { name: "gics", type: "link", link: { table: "gic" } },
    ],
  },
  { name: "index", columns: [{ name: "title", type: "string" }] },
  {
    name: "gic",
    columns: [
      { name: "sector", type: "link", link: { table: "sector" } },
      { name: "subIndustry", type: "link", link: { table: "subIndustry" } },
    ],
  },
  { name: "analystRating", columns: [{ name: "buy", type: "string" }] },
  { name: "sector", columns: [{ name: "name", type: "string" }] },
  { name: "subIndustry", columns: [{ name: "name", type: "string" }] },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Stock = InferredTypes["stock"];
export type StockRecord = Stock & XataRecord;

export type Index = InferredTypes["index"];
export type IndexRecord = Index & XataRecord;

export type Gic = InferredTypes["gic"];
export type GicRecord = Gic & XataRecord;

export type AnalystRating = InferredTypes["analystRating"];
export type AnalystRatingRecord = AnalystRating & XataRecord;

export type Sector = InferredTypes["sector"];
export type SectorRecord = Sector & XataRecord;

export type SubIndustry = InferredTypes["subIndustry"];
export type SubIndustryRecord = SubIndustry & XataRecord;

export type DatabaseSchema = {
  stock: StockRecord;
  index: IndexRecord;
  gic: GicRecord;
  analystRating: AnalystRatingRecord;
  sector: SectorRecord;
  subIndustry: SubIndustryRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL: "https://s-workspace-8e3sca.us-east-1.xata.sh/db/stock",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
